Week5CodeChallenge/Week5CodeChallenge/Models/ContactForm.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week5CodeChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string ProjectDescription { get; set; }
        public string Comment { get; set; }
    }
}

Week5CodeChallenge/Week5CodeChallenge/Models/ContactForms.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week5CodeChallenge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactFormsEntities2 : DbContext
    {
        public ContactFormsEntities2()
            : base("name=ContactFormsEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactForm> ContactForms { get; set; }
    }
}

Week5CodeChallenge/Week5CodeChallenge/Models/ContactForms.Designer.cs
// Default code generation is disabled for model 'C:\Users\Technologist\Documents\GitHub\Week5CodeChallenge\Week5CodeChallenge\Week5CodeChallenge\Models\ContactForms.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

Week5CodeChallenge/Week5CodeChallenge/Models/ContactForms.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Week5CodeChallenge/Week5CodeChallenge/Models/ContactFormsValidation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Week5CodeChallenge.Models
{
    [MetadataType(typeof(ContactFormsValidation))]

    public partial class ContactForm
    {

    }
    public class ContactFormsValidation
    {
        [Required(ErrorMessage="*"), MaxLength(50)]
        public string FirstName { get; set; }
        [Required(ErrorMessage="*"), MaxLength(50)]
        public string LastName { get; set; }
        [Required(ErrorMessage="*"), EmailAddress(ErrorMessage="*")]
        public string Email { get; set; }
        [Required(ErrorMessage="*")]
        public string PhoneNumber { get; set; }
        [Required(ErrorMessage="*"), MaxLength(50)]
        public string CompanyName { get; set; }
        [Required(ErrorMessage="*")]
        public string ProjectDescription { get; set; }
        [Required(ErrorMessage="*")]
        public string Comment { get; set; }
    }
}

Week5CodeChallenge/Week5CodeChallenge/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return View();
        }
        // GET: /About/Who

        public ActionResult Who()
        {
            

                return PartialView();    
        }
        // GET: /About/What

        public ActionResult What()
        {
            return PartialView();
        }
        // GET: /About/Why

        public ActionResult Why()
        {
            return PartialView();
        }
        // GET: /About/How

        public ActionResult How()
        {
            return PartialView();
        }
        // GET: /About/Where

        public ActionResult Where()
        {
            return PartialView();
        }
        

    }
}

Week5CodeChallenge/Week5CodeChallenge/Controllers/CareersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class CareersController : Controller
    {
        //
        // GET: /Careers/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Week5CodeChallenge/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/
        [HttpGet]
        public ActionResult Index()
        {
            Models.ContactForm cf = new Models.ContactForm();
            return View(cf);
        }
        //POST: /Home/Contact
        [HttpPost]
        public ActionResult Index(Models.ContactForm cf)
        {
            Models.ContactFormsEntities2 db = new Models.ContactFormsEntities2();
            db.ContactForms.Add(cf);
            //save changes
            db.SaveChanges();

            return RedirectToAction("ThankYou");
        }
        //GET: /Home/ThankYOU
        public ActionResult ThankYou()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Week5CodeChallenge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Week5CodeChallenge/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week5CodeChallenge.Controllers
{
    public class WorkController : Controller
    {
        //
        // GET: /Work/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week5CodeChallenge/Week5CodeChallenge/Views/About/How.cshtml
    <div class="mainAjax">
        <h2>How We Do It</h2>
        <span>Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</span>
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
    </div>

Week5CodeChallenge/Week5CodeChallenge/Views/About/Index.cshtml
@{
    ViewBag.Title = "Debrief";
}

<div id="mainAbout">
    <div id="ajax">
         <ul>
                <li class="wholink active" data-url="@Url.Action("Who", "About")">Who</li>
                <li class="whatlink" data-url="@Url.Action("What", "About")">What</li>
                <li class="whylink" data-url="@Url.Action("Why", "About")">Why</li>
                <li class="howlink" data-url="@Url.Action("How", "About")">How</li>
                <li class="wherelink" data-url="@Url.Action("Where", "About")">Where</li>
            </ul>
    </div>
    <div class="mainAbout">
        @Html.Partial("Who")  
        
    </div>
</div>

Week5CodeChallenge/Week5CodeChallenge/Views/About/What.cshtml
    <div class="mainAjax">
        <h2>What We Do</h2>
        <span>Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</span>
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
    </div>

Week5CodeChallenge/Week5CodeChallenge/Views/About/Where.cshtml
    <div class="mainAjax">
        <h2>It All Happens Here</h2>
        <span>Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</span>
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
    </div>

Week5CodeChallenge/Week5CodeChallenge/Views/About/Who.cshtml
    <div class="mainAjax">
        <h2>Meet the Team</h2>
        <span>Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</span>
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
  <div id="team">

<img style="padding:0 0 0 10px;" src="../../Content/Images/Ketenks.png" alt="The General: A Code Master" />
<img src="../../Content/Images/Gerton.png" alt="" />
<img src="../../Content/Images/Boyder.png" alt="" />
<img src="../../Content/Images/Layne.png" alt="" />
<img src="../../Content/Images/Bemilin.png" alt="" />

  </div>
          </div>

Week5CodeChallenge/Week5CodeChallenge/Views/About/Why.cshtml
    <div class="mainAjax">
        <h2>Why We Do It</h2>
        <span>Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</span>
        <p>"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."</p>
    </div>

Week5CodeChallenge/Week5CodeChallenge/Views/Careers/Index.cshtml
@{
    ViewBag.Title = "Careers";
}


<div id="mainCareers">
    <div id="bkgrnd" style="border-bottom:1px solid;">
<span><p>You Think You've Got What It Takes?</p></span>
        <div id="1car">
       
</div>
    <div id="2car">
     
    </div>
        <div id="2.5car" style="margin:380px 0 3px 15px;font-size:x-large;font-weight:bold;color:ghostwhite;">
<p style="font-size:xx-large;">We Only Look for 3 Things...</p>
    <ul style="list-style:none;">
        <li><p style="font-size:x-large;">PWN Some Noobs</p></li>
        <li><p style="font-size:x-large;">Have High Pain Tolerance</p></li>
        <li><p style="font-size:x-large;">Take Pleasure In the Results</p></li>
    </ul>
        </div>
       </div> 
    <div id="3car">
    <span>And This Fourth Thing:</span>
        <p>If you want a job, then read this, go to our contact page, fill out a contact form, set the Project Description as simply PWN and in the Comments section explain in your own words this passage with why it is so important for business and how you plan to apply it. Thanks, we'll see you there.</p>
        <span>1914 Translation by H. Rackham of Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</span>
        <p>"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."</p>

    </div>
</div>

Week5CodeChallenge/Week5CodeChallenge/Views/Contact/Index.cshtml
@model Week5CodeChallenge.Models.ContactForm

@{
    ViewBag.Title = "Contact Us";
}
<div id="mainContact">
<h2>Contact Us</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset style="display:inline-block;">
        <legend style="text-align:center;">ContactForm</legend>

        
 <div style="position:relative;float:left; margin-left:25%;">
        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <div class="editor-field" >
            @Html.EditorFor(model => model.FirstName)
            
        </div>
</div>
        <div >
        <div class="editor-label">
            @Html.LabelFor(model => model.LastName)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LastName)
            
        </div>
    </div>
        <div style="position:relative;float:left;margin-left:25%;">
        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            
        </div>
</div>
        <div >
        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNumber)
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNumber)
            
        </div>
</div>
        <div style="margin-left:37.5%;">
        <div class="editor-label">
            @Html.LabelFor(model => model.CompanyName)
            @Html.ValidationMessageFor(model => model.CompanyName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CompanyName)
            
        </div>
</div>
        <div style="position:relative;float:left;margin-left:0;">
        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectDescription)
            @Html.ValidationMessageFor(model => model.ProjectDescription)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.ProjectDescription)
            
        </div>
</div>
        <div style="position:relative;float:left;margin-left:3.5%;">
        <div class="editor-label">
            @Html.LabelFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Comment)
            
            
        </div>
</div>
        <p style="position:relative;float:left;">
            <input type="submit" value="Send" />
        </p>
        <p style="color:red;font-size:medium;font-weight:bold;position:relative;float:right;">*All Fields Are Required*</p>
        
    </fieldset>
}

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Week5CodeChallenge/Week5CodeChallenge/Views/Contact/ThankYou.cshtml
@{
    ViewBag.Title = "ThankYou";
}

<h2>Thank You</h2>
<div>
    <p>We will get back to you as soon as we are able. Until next time, <p>MercTec</p></p>
</div>

Week5CodeChallenge/Week5CodeChallenge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "MercTec";
}

<div id="mainHome">
    <div id="1h 2h">
        <img style="margin:0;paddig:0;width:100%;height:625px;border-bottom:1px solid;" src="../../Content/Images/MercTecSoldier.png" alt="" />
    </div>
    <div id="3h">
        
    </div>
    <div class="thirds">
        <h2>PWN</h2>
        <p>As the name suggests, it is a primary concern. You won't find noobs in any squad or platoon of ours. Every single soldier has been fully trained and debriefed for every mission in which he is deployed. Otherwise, he is simply not deployable. That takes the burden off of you. Be ready and prepare yourself to get to work and get the job done smoothly, efficiently and tactically with MercTec.</p>
   <p></p>
         </div>
    <div class="thirds">
        <h2>Pain</h2>
        <p>We endure all, to secure and protect those who have come into our confidence. We persevere through any misgiving or any mistake either within our own self-organizing units or for our delegates. This is all to avoid greater obstacles and greater casualties which may present themselves if necessary risks aren't taken or mitigated. And yes, we leave no man behind. Every soldier is accountable for their contribution to the completion of the mission.</p>
    </div>
    <div class="thirds">
        <h2>Pleasure</h2>
        <p>You aren't looking at your normal dev's. Each and every man, woman and sometimes very brilliant child was born to do this job. We thrive on the challenges that this work provides. Every soldier at MercTec brings a unique nuance to our development but we all have this one thing in common: we love it. </p>
    
    </div>
</div>

Week5CodeChallenge/Week5CodeChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>MercTec</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="logo">
            <img src="../../Content/Images/MercTecLogo1.png" alt="" />
        </div>
        <nav id="navbar">
            <ul>
                <li><a href="@Url.Action("Index", "Home")">Base</a></li>
                <li><a href="@Url.Action("Index", "About")">Debrief</a></li>
                <li><a href="@Url.Action("Index", "Work")">Projects</a></li>
                <li><a href="@Url.Action("Index", "Careers")">Careers</a></li>
                <li><a href="@Url.Action("Index", "Contact")">Contact Us</a></li>
            </ul>
        </nav>
    </header>

    <div class="main">
        @RenderBody()
    </div>
    
    <footer class="center">
       <span  style="text-align:left;">Copyright 2014 MercTec, LLC</span>
        <ul>
                             <li><a href="@Url.Action("Index", "Home")">Base</a></li>
                &nbsp;|&nbsp;<li><a href="@Url.Action("Index", "About")">Debrief</a></li>
                &nbsp;|&nbsp;<li><a href="@Url.Action("Index", "Work")">Projects</a></li>
                &nbsp;|&nbsp;<li><a href="@Url.Action("Index", "Careers")">Careers</a></li>
                &nbsp;|&nbsp;<li><a href="@Url.Action("Index", "Contact")">Contact Us</a></li>
        </ul>
    </footer>
   

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/Main")
</body>
</html>

Week5CodeChallenge/Week5CodeChallenge/Views/Work/Index.cshtml
@{
    ViewBag.Title = "Projects";
}

<div id="mainWork">
<h2>Current Projects</h2>
    <div class="fourths">
        <img src="../../Content/Images/GetinTouchProject.png" alt="" />
        <p>Get In Touch With Your Tools</p>
    </div>
    <div class="fourths">
        <img src="../../Content/Images/TeamProject.png" alt="" />
        <p>Team Assimilation</p>
    </div>
    <div class="fourths">
        <img src="../../Content/Images/HighTechProject.png" alt="" />
        <p>Bust Out the Tec!</p>
    </div>
    <div class="fourths">
        <img src="../../Content/Images/CompleteProject.png" alt="" />
        <p>Integrate Globally</p>
    </div>
    
</div>